---
overwrite: false
keepDistributor: false
prefer_grub_d: false
always_use_defaults: false
defaults:
  GRUB_TIMEOUT: 5
  GRUB_DEFAULT: "0"
  GRUB_DISABLE_SUBMENU: true
  GRUB_TIMEOUT_STYLE: menu
  GRUB_DISTRIBUTOR: "TorchOS"
  GRUB_CMDLINE_LINUX_DEFAULT: "quiet loglevel=3"
  GRUB_DISABLE_RECOVERY: true
