---
extraMounts:
- device: proc
  fs: proc
  mountPoint: /proc
- device: sys
  fs: sysfs
  mountPoint: /sys
- device: /dev
  mountPoint: /dev
  options: [ bind ]
- device: tmpfs
  fs: tmpfs
  mountPoint: /run
- device: /run/udev
  mountPoint: /run/udev
  options: [ bind ]
- device: efivarfs
  fs: efivarfs
  mountPoint: /sys/firmware/efi/efivars
  efi: true
# Layout rationale: docs/decisions/btrfs-layout.md. /.snapshots is created by snapper itself.
btrfsSubvolumes:
- mountPoint: /
  subvolume: /@
- mountPoint: /home
  subvolume: /@home
- mountPoint: /var/log
  subvolume: /@log
- mountPoint: /var/cache
  subvolume: /@cache
- mountPoint: /.snapshots
  subvolume: /@snapshots
mountOptions:
- filesystem: default
  options: [ defaults ]
- filesystem: btrfs
  options: [ defaults, noatime, compress=zstd:1 ]
  ssdOptions: [ discard=async ]
