---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
userSwapChoices: [ none ]
initialSwapChoice: none
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: erase
defaultPartitionTableType: gpt
defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs", "ext4", "xfs" ]
enableLuksAutomatedPartitioning: true
