---
defaultGroups: [ users, wheel, video, audio, input, render, torch-agent ]
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
availableShells: /bin/bash
userShell: /bin/bash
passwordRequirements:
  minLength: 6
  maxLength: -1
allowWeakPasswords: true
allowWeakPasswordsDefault: true
