---
showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
requirements:
  requiredStorage: 12
  requiredRam: 1.5
  internetCheckUrl: https://archlinux.org
  check: [ storage, ram, root ]
  required: [ storage, ram, root ]
